version: 2

models:
    - name: stg_products
      description: "Staging view for TPCH_SF1.PART with proper typing and audit columns"
      access: public
      groups:
          - name: product_data
            owner:
                # 'name' or 'email' is required; additional properties allowed
                name: Product Management
                email: product_management@acmeinc.com
                slack: product-data
                github: product-data-team
      config:
          contract:
              enforced: true
      columns:
          - name: part_id
            description: "Part key, cast to string."
            data_type: string
            tests:
                - not_null
                - unique

          - name: part_name
            description: "Part name, cast to string."
            data_type: string
            tests:
                - not_null

          - name: manufacturer
            description: "Manufacturer from source."
            data_type: string
            tests:
                - not_null

          - name: brand
            description: "Brand from source."
            data_type: string
            tests:
                - not_null

          - name: type
            description: "Type from source."
            data_type: string
